import { readFile } from 'node:fs/promises';

import { SOCIAL_PROTOCOL_EVENT_LAYOUT } from '../src/anchor-events.js';

interface Idl {
  readonly address: string;
  readonly events: readonly {
    readonly name: string;
    readonly discriminator: readonly number[];
  }[];
  readonly types: readonly {
    readonly name: string;
    readonly type: {
      readonly kind: string;
      readonly fields?: readonly {
        readonly name: string;
        readonly type: unknown;
      }[];
      readonly variants?: readonly { readonly name: string }[];
    };
  }[];
}

const expectedFields = {
  BlockStateChanged: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['block_edge', '"pubkey"'],
    ['blocker_identity', '"pubkey"'],
    ['subject_identity', '"pubkey"'],
    ['authority', '"pubkey"'],
    ['blocker_sequence', '"u64"'],
    ['edge_state_sequence', '"u64"'],
    ['active', '"bool"'],
    ['updated_at_slot', '"u64"'],
  ],
  CommunityCreated: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['community', '"pubkey"'],
    ['creator_identity', '"pubkey"'],
    ['authority', '"pubkey"'],
    ['community_nonce', '{"array":["u8",16]}'],
    ['creator_sequence', '"u64"'],
    ['manifest_hash', '{"array":["u8",32]}'],
    ['manifest_uri', '"string"'],
    ['governance_version', '"u16"'],
    ['governance_strategy_hash', '{"array":["u8",32]}'],
    ['visibility', '{"defined":{"name":"CommunityVisibility"}}'],
    ['membership_policy', '{"defined":{"name":"CommunityMembershipPolicy"}}'],
    ['membership_policy_sequence', '"u64"'],
    ['membership_sequence', '"u64"'],
    ['created_at_slot', '"u64"'],
  ],
  CommunityGovernanceUpdated: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['community', '"pubkey"'],
    ['creator_identity', '"pubkey"'],
    ['authority', '"pubkey"'],
    ['creator_sequence', '"u64"'],
    ['previous_governance_version', '"u16"'],
    ['governance_version', '"u16"'],
    ['previous_strategy_hash', '{"array":["u8",32]}'],
    ['governance_strategy_hash', '{"array":["u8",32]}'],
    ['updated_at_slot', '"u64"'],
  ],
  CommunityMembershipChanged: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['community', '"pubkey"'],
    ['membership', '"pubkey"'],
    ['member_identity', '"pubkey"'],
    ['actor_identity', '"pubkey"'],
    ['authority', '"pubkey"'],
    ['action', '{"defined":{"name":"CommunityMembershipAction"}}'],
    ['state', '{"defined":{"name":"CommunityMembershipState"}}'],
    ['state_sequence', '"u64"'],
    ['member_action_sequence', '"u64"'],
    ['actor_sequence', '"u64"'],
    ['membership_policy_sequence', '"u64"'],
    ['community_membership_sequence', '"u64"'],
    ['active_since_membership_sequence', '"u64"'],
    ['roles', '"u16"'],
    ['manifest_hash', '{"array":["u8",32]}'],
    ['manifest_uri', '"string"'],
    ['updated_at_slot', '"u64"'],
  ],
  DelegationCreated: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['delegation', '"pubkey"'],
    ['delegate_authority', '"pubkey"'],
    ['delegation_sequence', '"u64"'],
    ['identity_sequence', '"u64"'],
    ['scopes', '"u16"'],
    ['issued_at_root_rotation_count', '"u64"'],
    ['expires_at_slot', '"u64"'],
    ['issued_at_slot', '"u64"'],
  ],
  DelegationRevoked: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['delegation', '"pubkey"'],
    ['delegate_authority', '"pubkey"'],
    ['delegation_sequence', '"u64"'],
    ['identity_sequence', '"u64"'],
    ['delegation_state_sequence', '"u64"'],
    ['revoked_at_slot', '"u64"'],
  ],
  FollowStateChanged: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['follow_edge', '"pubkey"'],
    ['follower_identity', '"pubkey"'],
    ['subject_identity', '"pubkey"'],
    ['follower_sequence', '"u64"'],
    ['edge_state_sequence', '"u64"'],
    ['active', '"bool"'],
    ['updated_at_slot', '"u64"'],
  ],
  HandleClaimed: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['handle_claim', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['authority', '"pubkey"'],
    ['identity_sequence', '"u64"'],
    ['handle_hash', '{"array":["u8",32]}'],
    ['handle', '"string"'],
    ['claimed_at_slot', '"u64"'],
  ],
  HandleReleased: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['handle_claim', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['authority', '"pubkey"'],
    ['identity_sequence', '"u64"'],
    ['handle_hash', '{"array":["u8",32]}'],
    ['handle', '"string"'],
    ['released_at_slot', '"u64"'],
  ],
  IdentityCreated: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['root_authority', '"pubkey"'],
    ['identity_nonce', '{"array":["u8",16]}'],
    ['created_at_slot', '"u64"'],
  ],
  IdentityDeactivated: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['root_authority', '"pubkey"'],
    ['identity_sequence', '"u64"'],
    ['deactivated_at_slot', '"u64"'],
  ],
  PaymentAuthorityRotated: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['payment_config', '"pubkey"'],
    ['previous_authority', '"pubkey"'],
    ['new_authority', '"pubkey"'],
    ['policy_sequence', '"u64"'],
    ['rotated_at_slot', '"u64"'],
  ],
  PaymentConfigInitialized: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['payment_config', '"pubkey"'],
    ['upgrade_authority', '"pubkey"'],
    ['payment_authority', '"pubkey"'],
    ['fee_destination', '"pubkey"'],
    ['fee_bps', '"u16"'],
    ['policy_sequence', '"u64"'],
    ['enabled', '"bool"'],
    ['initialized_at_slot', '"u64"'],
  ],
  PaymentConfigUpdated: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['payment_config', '"pubkey"'],
    ['authority', '"pubkey"'],
    ['previous_fee_destination', '"pubkey"'],
    ['fee_destination', '"pubkey"'],
    ['previous_fee_bps', '"u16"'],
    ['fee_bps', '"u16"'],
    ['previous_enabled', '"bool"'],
    ['enabled', '"bool"'],
    ['policy_sequence', '"u64"'],
    ['updated_at_slot', '"u64"'],
  ],
  PostReferencePublished: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['post_reference', '"pubkey"'],
    ['author_identity', '"pubkey"'],
    ['authority', '"pubkey"'],
    ['post_nonce', '{"array":["u8",16]}'],
    ['author_sequence', '"u64"'],
    ['manifest_hash', '{"array":["u8",32]}'],
    ['manifest_uri', '"string"'],
    ['created_at_slot', '"u64"'],
  ],
  PostTombstoned: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['tombstone', '"pubkey"'],
    ['target_post', '"pubkey"'],
    ['author_identity', '"pubkey"'],
    ['author_sequence', '"u64"'],
    ['target_hash', '{"array":["u8",32]}'],
    ['reason', '{"defined":{"name":"TombstoneReason"}}'],
    ['created_at_slot', '"u64"'],
  ],
  ProposalCreated: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['community', '"pubkey"'],
    ['proposal', '"pubkey"'],
    ['proposer_identity', '"pubkey"'],
    ['authority', '"pubkey"'],
    ['proposer_sequence', '"u64"'],
    ['previous_community_sequence', '"u64"'],
    ['manifest_hash', '{"array":["u8",32]}'],
    ['manifest_uri', '"string"'],
    ['governance_version', '"u16"'],
    ['governance_strategy_hash', '{"array":["u8",32]}'],
    ['voting_model', '{"defined":{"name":"GovernanceVotingModel"}}'],
    ['eligible_member_count', '"u64"'],
    ['community_membership_sequence', '"u64"'],
    ['opens_at_slot', '"u64"'],
    ['closes_at_slot', '"u64"'],
    ['quorum_bps', '"u16"'],
    ['approval_bps', '"u16"'],
    ['proposal_state_sequence', '"u64"'],
    ['created_at_slot', '"u64"'],
  ],
  ProposalFinalized: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['community', '"pubkey"'],
    ['proposal', '"pubkey"'],
    ['finalizer', '"pubkey"'],
    ['proposal_state_sequence', '"u64"'],
    ['eligible_member_count', '"u64"'],
    ['yes_votes', '"u64"'],
    ['no_votes', '"u64"'],
    ['abstain_votes', '"u64"'],
    ['participating_votes', '"u64"'],
    ['decisive_votes', '"u64"'],
    ['quorum_bps', '"u16"'],
    ['approval_bps', '"u16"'],
    ['quorum_met', '"bool"'],
    ['approval_met', '"bool"'],
    ['outcome', '{"defined":{"name":"GovernanceProposalOutcome"}}'],
    ['finalized_at_slot', '"u64"'],
  ],
  ProfileReferenceUpdated: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['authority', '"pubkey"'],
    ['sequence', '"u64"'],
    ['previous_manifest_hash', '{"array":["u8",32]}'],
    ['manifest_hash', '{"array":["u8",32]}'],
    ['manifest_uri', '"string"'],
    ['updated_at_slot', '"u64"'],
    ['profile_schema_version', '"u16"'],
  ],
  ProtocolInitialized: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['initialized_at_slot', '"u64"'],
  ],
  ReactionStateChanged: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['reaction_reference', '"pubkey"'],
    ['reactor_identity', '"pubkey"'],
    ['target_post', '"pubkey"'],
    ['authority', '"pubkey"'],
    ['reaction_kind', '"u8"'],
    ['reactor_sequence', '"u64"'],
    ['reaction_state_sequence', '"u64"'],
    ['active', '"bool"'],
    ['updated_at_slot', '"u64"'],
  ],
  RecoveryApproved: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['recovery_policy', '"pubkey"'],
    ['recovery_request', '"pubkey"'],
    ['guardian', '"pubkey"'],
    ['guardian_index', '"u8"'],
    ['policy_sequence', '"u64"'],
    ['approval_count', '"u8"'],
    ['threshold', '"u8"'],
    ['approved_at_slot', '"u64"'],
  ],
  RecoveryCancelled: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['recovery_policy', '"pubkey"'],
    ['recovery_request', '"pubkey"'],
    ['cancelled_by_root_authority', '"pubkey"'],
    ['target_root_authority', '"pubkey"'],
    ['policy_sequence', '"u64"'],
    ['identity_sequence', '"u64"'],
    ['root_rotation_count', '"u64"'],
    ['cancelled_at_slot', '"u64"'],
  ],
  RecoveryExecuted: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['recovery_policy', '"pubkey"'],
    ['recovery_request', '"pubkey"'],
    ['executor', '"pubkey"'],
    ['previous_root_authority', '"pubkey"'],
    ['new_root_authority', '"pubkey"'],
    ['policy_sequence', '"u64"'],
    ['approval_count', '"u8"'],
    ['threshold', '"u8"'],
    ['identity_sequence', '"u64"'],
    ['rotation_count', '"u64"'],
    ['executed_at_slot', '"u64"'],
  ],
  RecoveryPolicyConfigured: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['recovery_policy', '"pubkey"'],
    ['root_authority', '"pubkey"'],
    ['policy_sequence', '"u64"'],
    ['identity_sequence', '"u64"'],
    ['root_rotation_count', '"u64"'],
    ['guardians', '{"vec":"pubkey"}'],
    ['threshold', '"u8"'],
    ['delay_slots', '"u64"'],
    ['configured_at_slot', '"u64"'],
  ],
  RecoveryPolicyDisabled: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['recovery_policy', '"pubkey"'],
    ['root_authority', '"pubkey"'],
    ['policy_sequence', '"u64"'],
    ['identity_sequence', '"u64"'],
    ['root_rotation_count', '"u64"'],
    ['disabled_at_slot', '"u64"'],
  ],
  RecoveryRequested: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['recovery_policy', '"pubkey"'],
    ['recovery_request', '"pubkey"'],
    ['requesting_guardian', '"pubkey"'],
    ['request_nonce', '{"array":["u8",16]}'],
    ['policy_sequence', '"u64"'],
    ['current_root_authority', '"pubkey"'],
    ['identity_sequence', '"u64"'],
    ['root_rotation_count', '"u64"'],
    ['target_root_authority', '"pubkey"'],
    ['threshold', '"u8"'],
    ['guardian_count', '"u8"'],
    ['approval_count', '"u8"'],
    ['requested_at_slot', '"u64"'],
    ['execute_after_slot', '"u64"'],
  ],
  RootAuthorityRotated: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['identity', '"pubkey"'],
    ['previous_root_authority', '"pubkey"'],
    ['new_root_authority', '"pubkey"'],
    ['identity_sequence', '"u64"'],
    ['rotation_count', '"u64"'],
    ['rotated_at_slot', '"u64"'],
  ],
  SubscriptionOfferingCreated: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['payment_config', '"pubkey"'],
    ['offering', '"pubkey"'],
    ['creator_identity', '"pubkey"'],
    ['root_authority', '"pubkey"'],
    ['offering_nonce', '{"array":["u8",16]}'],
    ['manifest_hash', '{"array":["u8",32]}'],
    ['manifest_uri', '"string"'],
    ['price_lamports', '"u64"'],
    ['billing_interval', '{"defined":{"name":"SubscriptionInterval"}}'],
    ['recipient_splits', '{"vec":{"defined":{"name":"PaymentSplit"}}}'],
    ['refund_policy_hash', '{"array":["u8",32]}'],
    ['max_protocol_fee_bps', '"u16"'],
    ['creator_root_rotation_count', '"u64"'],
    ['creator_sequence', '"u64"'],
    ['offering_state_sequence', '"u64"'],
    ['created_at_slot', '"u64"'],
  ],
  SubscriptionOfferingRetired: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['offering', '"pubkey"'],
    ['creator_identity', '"pubkey"'],
    ['root_authority', '"pubkey"'],
    ['manifest_hash', '{"array":["u8",32]}'],
    ['creator_sequence', '"u64"'],
    ['offering_state_sequence', '"u64"'],
    ['retired_at_slot', '"u64"'],
  ],
  SubscriptionSettled: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['payment_config', '"pubkey"'],
    ['offering', '"pubkey"'],
    ['receipt', '"pubkey"'],
    ['entitlement', '"pubkey"'],
    ['creator_identity', '"pubkey"'],
    ['payer_identity', '"pubkey"'],
    ['payer_authority', '"pubkey"'],
    ['receipt_nonce', '{"array":["u8",16]}'],
    ['payment_kind', '{"defined":{"name":"PaymentKind"}}'],
    ['payer_root_rotation_count', '"u64"'],
    ['payment_policy_sequence', '"u64"'],
    ['offering_state_sequence', '"u64"'],
    ['offering_manifest_hash', '{"array":["u8",32]}'],
    ['refund_policy_hash', '{"array":["u8",32]}'],
    ['gross_lamports', '"u64"'],
    ['fee_bps', '"u16"'],
    ['fee_destination', '"pubkey"'],
    ['fee_lamports', '"u64"'],
    ['distributable_lamports', '"u64"'],
    ['recipient_splits', '{"vec":{"defined":{"name":"PaymentSplit"}}}'],
    ['recipient_amounts', '{"vec":"u64"}'],
    ['entitlement_state_sequence', '"u64"'],
    ['settlement_count', '"u64"'],
    ['entitlement_from_timestamp', '"i64"'],
    ['entitlement_until_timestamp', '"i64"'],
    ['paid_at_timestamp', '"i64"'],
    ['paid_at_slot', '"u64"'],
  ],
  VoteCast: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['community', '"pubkey"'],
    ['proposal', '"pubkey"'],
    ['vote', '"pubkey"'],
    ['voter_identity', '"pubkey"'],
    ['membership', '"pubkey"'],
    ['authority', '"pubkey"'],
    ['voter_sequence', '"u64"'],
    ['membership_state_sequence', '"u64"'],
    ['proposal_state_sequence', '"u64"'],
    ['choice', '{"defined":{"name":"GovernanceVoteChoice"}}'],
    ['yes_votes', '"u64"'],
    ['no_votes', '"u64"'],
    ['abstain_votes', '"u64"'],
    ['cast_at_slot', '"u64"'],
  ],
  WokeTipSettled: [
    ['event_version', '"u16"'],
    ['config', '"pubkey"'],
    ['payment_config', '"pubkey"'],
    ['receipt', '"pubkey"'],
    ['payer_identity', '"pubkey"'],
    ['payer_authority', '"pubkey"'],
    ['recipient_identity', '"pubkey"'],
    ['recipient_destination', '"pubkey"'],
    ['receipt_nonce', '{"array":["u8",16]}'],
    ['payment_kind', '{"defined":{"name":"PaymentKind"}}'],
    ['payer_root_rotation_count', '"u64"'],
    ['payment_policy_sequence', '"u64"'],
    ['gross_lamports', '"u64"'],
    ['fee_bps', '"u16"'],
    ['fee_destination', '"pubkey"'],
    ['fee_lamports', '"u64"'],
    ['distributable_lamports', '"u64"'],
    ['recipient_lamports', '"u64"'],
    ['paid_at_timestamp', '"i64"'],
    ['paid_at_slot', '"u64"'],
  ],
} as const;

const idlUrl = new URL('../../../target/idl/social_protocol.json', import.meta.url);
const idl = JSON.parse(await readFile(idlUrl, 'utf8')) as Idl;

assertEqual('program ID', idl.address, SOCIAL_PROTOCOL_EVENT_LAYOUT.programId);
assertEqual('event count', idl.events.length, 33);
assertEqual('decoder event count', Object.keys(SOCIAL_PROTOCOL_EVENT_LAYOUT.events).length, 33);
assertEqual(
  'event name set',
  JSON.stringify(idl.events.map((event) => event.name).sort()),
  JSON.stringify(Object.keys(SOCIAL_PROTOCOL_EVENT_LAYOUT.events).sort()),
);
assertEqual(
  'decoder layout specification set',
  JSON.stringify(Object.keys(expectedFields).sort()),
  JSON.stringify(Object.keys(SOCIAL_PROTOCOL_EVENT_LAYOUT.events).sort()),
);

for (const [name, discriminator] of Object.entries(SOCIAL_PROTOCOL_EVENT_LAYOUT.events)) {
  const idlEvent = idl.events.find((event) => event.name === name);
  assertEqual(
    `${name} discriminator`,
    JSON.stringify(idlEvent?.discriminator),
    JSON.stringify(discriminator),
  );

  const idlType = idl.types.find((type) => type.name === name);
  const actual = idlType?.type.fields?.map((field) => [field.name, JSON.stringify(field.type)]);
  assertEqual(
    `${name} fields`,
    JSON.stringify(actual),
    JSON.stringify(expectedFields[name as keyof typeof expectedFields]),
  );
}

const tombstoneReason = idl.types.find((type) => type.name === 'TombstoneReason');
assertEqual(
  'TombstoneReason variants',
  JSON.stringify(tombstoneReason?.type.variants?.map((variant) => variant.name)),
  JSON.stringify(['UserRequest', 'Safety', 'Other']),
);

assertEnumVariants('GovernanceVotingModel', ['OneActiveMemberOneVote']);
assertEnumVariants('GovernanceVoteChoice', ['Yes', 'No', 'Abstain']);
assertEnumVariants('GovernanceProposalOutcome', ['Pending', 'Accepted', 'Rejected']);
assertEnumVariants('RecoveryRequestState', ['Pending', 'Cancelled', 'Executed']);
assertEnumVariants('PaymentKind', ['WokeTip', 'WeeklySubscription']);
assertEnumVariants('SubscriptionInterval', ['Week']);

process.stdout.write('Checked-in Anchor event decoder exhaustively matches target IDL.\n');

function assertEqual(label: string, actual: unknown, expected: unknown): void {
  if (actual !== expected) {
    throw new Error(`${label} drifted from the checked-in Anchor decoder.`);
  }
}

function assertEnumVariants(name: string, expected: readonly string[]): void {
  const definition = idl.types.find((type) => type.name === name);
  assertEqual(
    `${name} variants`,
    JSON.stringify(definition?.type.variants?.map((variant) => variant.name)),
    JSON.stringify(expected),
  );
}
